### ISSUE TITLE
HA Liquid-Check Installation

### ISSUE THREAD

**Issue by MSacher** [shivan/homeassistant-liquidcheck#1]
Hallo,
das Repository liquid-check wird mir im HACS leider nicht angezeigt. Ich habe dann alle Files manuell nach config/custom_components/liquid-check kopiert. Allerdings  wird mir die Integration in HA nicht angezeigt, d.h. ich kann sie auch nicht konfigurieren. Bei anderen Repositories hat alles funktioniert (z.B. Meross-lan), aber hier mache ich wohl etwas falsch ...

**Comment by shivan** [comment]
Hi!
ich bin noch bei der Integration. Mein Merge-Request wurde leider noch nicht aufgenommen.

Genau, manuell sollte es funktionieren. 

Bei mir liegt das unter `/home/homeassistant/.homeassistant/custom_components/liquid-check`

Leider gibt es aber kein Icon dafür - da auch dieser Merge-Request noch nicht akzeptiert wurde.

Steht im Logfile irgendwas?

**Comment by MSacher** [comment]
Hallo,
ich habe folgenden Log-Eintrag:

ERROR (SyncWorker_3) [homeassistant.loader] Error parsing manifest.json file at /config/custom_components/liquid-check/manifest.json: unexpected character: line 7 column 1 (char 6)

**Comment by shivan** [comment]
Hi,

hast du die neueste Version aus dem Repository?

Die von dir genannte Datei sollte so aussehen:

```
{
  "domain": "liquid-check",
  "name": "Liquid-Check",
  "codeowners": ["@shivan"],
  "config_flow": true,
  "dependencies": [],
  "documentation": "https://github.com/shivan/homeassistant-liquidcheck",
  "iot_class": "local_polling",
  "issue_tracker": "https://github.com/shivan/homeassistant-liquidcheck/issues",
  "requirements": [],
  "version": "1.0.0"
}
```


Notfalls könntest du den Inhalt  von manifest.json damit mal ersetzen:

```
{
  "domain": "liquid-check",
  "version": "1.0.0",
  "name": "Liquid-Check",
  "documentation": "https://github.com/shivan/homeassistant-liquidcheck",
  "config_flow": true,
  "dependencies": [],
  "codeowners": ["@shivan"],
  "requirements": [],
  "iot_class": "local_polling"
}
```
allerdings wurde das von HACS bemängelt, deswegen habe ich das ins Obere korrigiert

**Comment by MSacher** [comment]
Ich probiere das morgen mal aus ...

**Comment by MSacher** [comment]
Hallo,
ich habe eine Menge Blödsinn aus dem Repository kopiert (nur die Dateinamen passten :( ). Nachdem alles richtig kopiert wurde, funktioniert die Anzeige des Liquid-Check auch perfekt. Vielen Dank.
